### PR TITLE
Grammatical errors, rephrasing, added legal disclaimer.

### PR DESCRIPTION
**Pull request by DavidScann**
Line 9, 10 has been updated to include a legal disclaimer regarding our association with SEGA. Which is none.

### CODE REVIEW

**Comment by DavidScann** [comment]
I forgot one grammatical error. I don't know how to edit this PR though 💀

**Comment by DavidScann** [comment]
ohhh that's how you do it

**Review by DavidScann — COMMENTED** [review]
accidentally removed line 1: `# AstroDX`

**Review by 2394425147 — APPROVED** [review]
lgtm

**Pull request merged**
